name: .NET

on:
  workflow_dispatch:
  push:
    branches: main
  
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Build
      shell: pwsh
      run: |
        .\build.ps1
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: setup-artifact
        path: "./MSI/Debug/Setup.MiningForGold.msi"
