name: .NET

on:
  workflow_dispatch:
  
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        NUGET_RESTORE_MSBUILD_ARGS: '/p:RestoreProjectFilterMode=""inclusionlist""'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore "Mining For Gold - Workflow.sln"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        NUGET_RESTORE_MSBUILD_ARGS: '/p:RestoreProjectFilterMode=""inclusionlist""'
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Build Solution
      run: |
        msbuild.exe "Mining For Gold - Workflow.sln" /nologo /nr:false /p:DeployOnBuild=true /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    
